language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t docker-react -f Dockerfile.dev .
 
script:
 - docker run -e CI=true docker-react npm run test

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-simplereact"
 env: "DockerSimplereact-env"
 bucket_name: "elasticbeanstalk-us-east-2-515993178835"
 bucket_path: "docker-simplereact"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
